network:
  version: 2
  renderer: networkd
  ethernets:
    ethLAN0:
      dhcp4: yes
      dhcp6: no
      accept-ra: no
      link-local: []      # Disable automatic linkâ€‘local assignment
      optional: true

