network:
  version: 2
  renderer: networkd
  ethernets:
    l4tbr0:
      dhcp4: no
      dhcp6: no
      accept-ra: no
      link-local: []      # Disable automatic linkâ€‘local assignment
      optional: true

