network:
  version: 2
  renderer: networkd
  ethernets:
    ethLAN2:
      mtu: 9000
      dhcp4: no
      dhcp6: no
      accept-ra: no
      addresses:
        - 10.10.2.1/24
      optional: true

    ethLAN3:
      mtu: 9000
      dhcp4: no
      dhcp6: no
      accept-ra: no
      addresses:
        - 10.10.3.1/24
      optional: true

    ethLAN4:
      addresses:
        - 192.168.30.25/24
      dhcp6: no
      accept-ra: no
      link-local: []      # Disable automatic linkâ€‘local assignment
      optional: true

    ethLAN5:
      mtu: 9000
      dhcp4: no
      dhcp6: no
      accept-ra: no
      addresses:
        - 10.10.5.1/24
      optional: true

